### ISSUE TITLE
Download Link

### ISSUE THREAD

**Issue by steno916** [beeware/Python-Android-support#2]
The download link to download the currently build binaries is broken. Here is the xml error.

`<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
Python-Android-support/3.6/Python-3.6-Android-support.b1.tar.gz
</Key>
<RequestId>44D2C02E0C3A8FAA</RequestId>
<HostId>
MkuqB/xnRIQg9uPCQ4qbJHb0obEWJslHG6lNeWK2XPRzrTuiUFbvitPJ+Zf4Lum1ypm5jS5SAqw=
</HostId>
</Error>`

**Comment by freakboy3742** [comment]
This project has been massively reworked by some work by @paulproteus; closing this issue as it no longer applies.
