### ISSUE TITLE
makefile has missing/bad paths

### ISSUE THREAD

**Issue by steno916** [beeware/Python-Android-support#3]
The makefile has missing ranlib and readelf paths for x86 and x86_64.  The rest of the paths for these abi's are missing the bin folder.

`# # ABI=x86
# HOST_TRIPLE-x86=i686-linux-android
# CC-x86=$(BUILD_NDK_TOOLCHAIN)/bin/clang --target=i686-linux-android$(ANDROID_API) --gcc-toolchain=$(ANDROID_NDK_ROOT)/toolchains/llvm/prebuilt/$(BUILD_TAG)
# CXX-x86=$(BUILD_NDK_TOOLCHAIN)/bin/i686-linux-android$(ANDROID_API)-clang++
# LD-x86=$(BUILD_NDK_TOOLCHAIN)/bin/i686-linux-android-ld
# AR-x86=$(BUILD_NDK_TOOLCHAIN)/bin/i686-linux-android-ar
# RANLIB-x86=$(BUILD_NDK_TOOLCHAIN)/bin/i686-linux-android-ranlib
# READELF-x86=$(BUILD_NDK_TOOLCHAIN)/bin/i686-linux-android-readelf

# # ABI=x86_64
# HOST_TRIPLE-x86_64=x86_64-linux-android
# CC-x86_64=$(BUILD_NDK_TOOLCHAIN)/bin/clang --target=x86_64-linux-android$(ANDROID_API) --gcc-toolchain=$(ANDROID_NDK_ROOT)/toolchains/llvm/prebuilt/$(BUILD_TAG)
# CXX-x86_64=$(BUILD_NDK_TOOLCHAIN)/bin/x86_64-linux-android$(ANDROID_API)-clang++
# LD-x86_64=$(BUILD_NDK_TOOLCHAIN)/bin/x86_64-linux-android-ld
# AR-x86_64=$(BUILD_NDK_TOOLCHAIN)/bin/x86_64-linux-android-ar
# RANLIB-x86_64=$(BUILD_NDK_TOOLCHAIN)/bin/x86_64-linux-android-ranlib
# READELF-x86_64=$(BUILD_NDK_TOOLCHAIN)/bin/x86_64-linux-android-readelf`

**Comment by freakboy3742** [comment]
This project has been massively reworked by some work by @paulproteus; closing this issue as it no longer applies.
