### ISSUE TITLE
Shrink size to ~200MB

### ISSUE THREAD

**Issue by paulproteus** [beeware/Python-Android-support#4]
A first pass at shrinking the support package to 200MB would be nice, since it's currently a 500MB monster.

The following might be quick, and if so, might be worth the time ASAP.

- Using the blacklist of files that we use on iOS.
- Enabling compression within ZIP files created within the build process.

**Comment by freakboy3742** [comment]
I'll close this ticket; but I'll open a new one to track to the general issue of pruning remaining content from the output artefact.
